# Generated by Django 3.2.8 on 2025-01-05 20:57

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the book', max_length=255)),
                ('author', models.CharField(help_text='Author of the book', max_length=255)),
                ('published_date', models.DateField(help_text='Published date of the book')),
                ('genre', models.CharField(help_text='Genre of the book', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the book', max_digits=10)),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
